//
// Created by lukasz on 24.10.16.
//

#ifndef HERKULEX_SERVO_CONTROLLER_HERKULEX_SERVO_CONTROLLER_NODE_H
#define HERKULEX_SERVO_CONTROLLER_HERKULEX_SERVO_CONTROLLER_NODE_H

#include "HerkulexController.h"
#include "ros/ros.h"

#endif //HERKULEX_SERVO_CONTROLLER_HERKULEX_SERVO_CONTROLLER_NODE_H
